# Generated by Django 3.2 on 2022-10-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie',
            field=models.ManyToManyField(related_name='actor', to='movies.Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
